services:
  factorio-prometheus-exporter:
    build:
      context: .
      args:
        REPO_URL: https://github.com/Factorio-Just-For-Fun/factorio-prometheus-exporter.git
    ports:
      - "8000:8000"  # Maps port 8000 on host to port 8000 in container
    volumes:
      - "./config.yaml:/app/config.yaml"
    environment:
      PYTHONUNBUFFERED: "1"
