services:
  factorio-prometheus-exporter:
    build:
      context: .
      args:
        REPO_URL: https://github.com/Factorio-Just-For-Fun/factorio-prometheus-exporter.git
    ports:
      - "8000:8000"  # Maps port 8000 on host to port 8000 in container
    volumes:
      - "./config.yaml:/app/config.yaml"
    environment:
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
      
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /dev/kmsg:/dev/kmsg
    ports:
      - "8080:8081"
    restart: unless-stopped

  portainer_agent:
    image: portainer/agent:2.19.5
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - './Grafana:/var/lib/grafana'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - './Prometheus/etc/:/etc/prometheus/'
      - './Prometheus/data:/prometheus'

    restart: always